[[commands]]
help = "Switch this Mac to the latest configuration"
name = "tilde"
command = "darwin-rebuild switch --flake .#"
category = "runtime"

[[commands]]
package = "nixfmt"
category = "development"

[[commands]]
package = "cachix"
category = "development"

[[commands]]
package = "statix"
category = "development"

[[commands]]
package = "git-crypt"
category = "development"
