[[commands]]
help = "Switch this Mac to the latest configuration"
name = "switch"
command = "nix run .#switch"
category = "runtime"

[[commands]]
package = "nixfmt"
category = "linting"

[[commands]]
package = "cachix"
category = "development"

[[commands]]
package = "statix"
category = "linting"

[[commands]]
package = "git-crypt"
category = "development"

[[commands]]
package = "dhall"
category = "development"

[[commands]]
package = "dhall-json"
category = "development"

[[commands]]
package = "taplo-cli"
category = "linting"
