[[commands]]
package = "nixfmt"
category = "development"

[[commands]]
package = "cachix"
category = "development"

[[commands]]
package = "statix"
category = "development"

[[commands]]
package = "git-crypt"
category = "development"
