name: Setup
description: "Sets up the workflow"
inputs:
  nix_system:
    description: Nix system to use (e.g., `aarch64-darwin`, `x86_64-linux`)
    required: true
  attic_token:
    description: Token for Attic cache
    required: true
  cachix_auth_token:
    description: Auth token for reading and writing to Cachix
    required: true
  pragmatapro_deploy_key:
    description: Deploy key for PragmataPro repository
    required: true
  secrets_deploy_key:
    description: Deploy key for secrets repository
    required: true
runs:
  using: "composite"
  steps:
    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v20
      with:
        source-url: "https://install.lix.systems/lix/lix-installer-${{ inputs.nix_system }}"
        extra-conf: |
          accept-flake-config = true
          max-jobs = auto
    - name: Add SSH keys to ssh-agent
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: |
          ${{ inputs.pragmatapro_deploy_key }}
          ${{ inputs.secrets_deploy_key }}
    - name: Setup Attic cache
      uses: ryanccn/attic-action@v0
      with:
        endpoint: https://cache.e10.camp
        cache: tilde
        token: ${{ inputs.attic_token }}
    - name: Use Cachix store
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ inputs.cachix_auth_token }}
        installCommand: nix profile install github:NixOS/nixpkgs/nixpkgs-unstable#cachix
        extraPullNames: tilde,nix-community
        name: tilde
