task:
  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  timeout_in: 120m

  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest

  matrix:
    - name: build
      install_script:
        - sh <(curl -L https://nixos.org/nix/install)
      build_script:
        - |
          export DIR=$(mktemp -d)
          cp -r * $DIR
          cd $DIR
          git init
          git add .
        - /nix/var/nix/profiles/default/bin/nix flake check --extra-experimental-features nix-command --extra-experimental-features flakes --show-trace
        # - /nix/var/nix/profiles/default/bin/nix build .#darwinConfigurations.st-eturkeltaub2.system --extra-experimental-features nix-command --extra-experimental-features flakes --show-trace
