task:
  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  timeout_in: 120m

  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest

  matrix:
    - name: build
      environment:
        CIRRUS_USER_PERMISSION: admin
        # SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        CACHIX_AUTH_TOKEN: ENCRYPTED[7e00c3086fa51a56acd871027b2e32003e93224b6bc0b978d39ef1b05bc65a458c71c8a6663b508a19eeba05560b37e3]
        GIT_CRYPT_TOKEN: ENCRYPTED[415884b4c6e8e899e8808b433a8fc0c153f095c6fef7db2963b7ab0110bd53b9d79e5d37a7543987f34290c7c8c70686]
        PRAGMATAPRO_SSH_KEY: ENCRYPTED[c1d1c03146c8dfdd70f6a982cf45bef1ecc468d7af6525048bdde512516e809b8ee9b520f31dfc73a3d4244cfcfa5355]
      install_script:
        - sh <(curl -L https://nixos.org/nix/install)
        - mkdir -p $HOME/.config/nix
        - echo "extra-experimental-features = nix-command flakes" >> $HOME/.config/nix/nix.conf
        - echo "trusted-users = admin" >> $HOME/.config/nix/nix.conf

      ssh_agent_script:
        - eval "$(ssh-agent -s)"
        - mkdir $HOME/.ssh
        - |
          echo "
            Host *
              AddKeysToAgent yes
              IdentityFile /tmp/pragmatapro-key
          " >> $HOME/.ssh/config
        - echo "$PRAGMATAPRO_SSH_KEY" > /tmp/pragmatapro-key
        - chmod 0400 /tmp/pragmatapro-key
        - ssh-add --apple-use-keychain /tmp/pragmatapro-key
        - echo $SSH_AUTH_SOCK
        - git clone git@github.com/ethnt/pragmatapro.git

        - echo "$GIT_CRYPT_TOKEN" | base64 -d > /tmp/git-crypt-key.asc
        - brew install git-crypt
        - git-crypt unlock /tmp/git-crypt-key.asc
        - git add .
        - /nix/var/nix/profiles/default/bin/nix build .#darwinConfigurations.st-eturkeltaub2.system --show-trace

      cachix_script:
        - /nix/var/nix/profiles/default/bin/nix develop -c "cachix" "push" "tilde" "result/"
        # - /nix/var/nix/profiles/default/bin/nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --show-trace -c "git-crypt" "unlock" "/tmp/git-crypt-key.asc"
        # - /nix/var/nix/profiles/default/bin/nix flake check --extra-experimental-features nix-command --extra-experimental-features flakes --show-trace
        # - /nix/var/nix/profiles/default/bin/nix build .#darwinConfigurations.st-eturkeltaub2.system --extra-experimental-features nix-command --extra-experimental-features flakes --show-trace
