task:
  timeout_in: 120m

  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest

  environment:
    CIRRUS_USER_PERMISSION: admin
    CACHIX_AUTH_TOKEN: ENCRYPTED[7e00c3086fa51a56acd871027b2e32003e93224b6bc0b978d39ef1b05bc65a458c71c8a6663b508a19eeba05560b37e3]
    GIT_CRYPT_TOKEN: ENCRYPTED[415884b4c6e8e899e8808b433a8fc0c153f095c6fef7db2963b7ab0110bd53b9d79e5d37a7543987f34290c7c8c70686]

    NIX_INSTALLER_CHANNELS: nixpkgs=https://nixos.org/channels/nixpkgs-unstable
    NIX_INSTALLER_EXTRA_CONF: |
      extra-experimental-features = nix-command flakes
      trusted-users = admin
      extra-platforms = x86_64-darwin

    PATH: "$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/per-user/$USER/profile/bin:$PATH"
    NIX_PATH: /nix/var/nix/profiles/per-user/root/channels

  matrix:
    - name: build (st-eturkeltaub2)
      install_script:
        - curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix > nix-installer.sh
        - chmod +x nix-installer.sh
        - ./nix-installer.sh install --no-confirm
      prepare_nix_env_script:
        - nix-env -iA cachix -f https://cachix.org/api/v1/install
        - nix-channel --add https://nixos.org/channels/nixpkgs-unstable
        - nix-channel --update
      git_crypt_script:
        - echo "$GIT_CRYPT_TOKEN" | base64 -d > /tmp/git-crypt-key.asc
        - nix-env -iA nixpkgs.git-crypt
        - git-crypt unlock /tmp/git-crypt-key.asc
        - git add .
      cachix_script:
        - nix-env -iA nixpkgs.cachix
        - cachix use tilde
      build_script:
        - sudo nix-store --repair --verify --check-contents
        - nix build .#darwinConfigurations.st-eturkeltaub2.system --accept-flake-config --show-trace
      cachix_upload_script:
        - cachix push tilde result/
