task:
  # Use the maximum timeout. Needed when rebuilding packages on a channel update.
  timeout_in: 120m

  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest

  matrix:
    - name: build
      environment:
        GIT_CRYPT_TOKEN: ENCRYPTED[415884b4c6e8e899e8808b433a8fc0c153f095c6fef7db2963b7ab0110bd53b9d79e5d37a7543987f34290c7c8c70686]
        CIRRUS_USER_PERMISSION: admin
      install_script:
        - sh <(curl -L https://nixos.org/nix/install)
        - echo "extra-experimental-features = nix-command flakes" >> /etc/nix/nix.conf
      build_script:
        - echo "$GIT_CRYPT_TOKEN" | base64 -d > /tmp/git-crypt-key.asc
        - /nix/var/nix/profiles/default/bin/nix develop --extra-experimental-features nix-command --extra-experimental-features flakes --show-trace -c "git-crypt" "unlock" "/tmp/git-crypt-key.asc"
        # - /nix/var/nix/profiles/default/bin/nix flake check --extra-experimental-features nix-command --extra-experimental-features flakes --show-trace
        # - /nix/var/nix/profiles/default/bin/nix build .#darwinConfigurations.st-eturkeltaub2.system --extra-experimental-features nix-command --extra-experimental-features flakes --show-trace
