macos_instance:
  image: ghcr.io/cirruslabs/macos-monterey-base:latest

task:
  name: Install Nix
  script: |
    sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
    cert_file=/nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt
    export NIX_SSL_CERT_FILE=$cert_file
    sudo launchctl setenv NIX_SSL_CERT_FILE "$cert_file"
    echo "/nix/var/nix/profiles/default/bin" >> "$PATH"
    echo "/nix/var/nix/profiles/per-user/$USER/profile/bin" >> "$PATH"
    nix build .#darwinConfigurations.eMac.system --show-trace
