keys:
  - &user_ethan age10539mc6shf02hpa8huyjktdw3nfyavxdg8pt247wwvq4xrv8h5zs8nc0k0
  - &host_eMac age1hqq6znfaedyrmqkqqnaafa243cus77nts3e5vunxdl5xkfm6ffgqmf70r8

creation_rules:
  - path_regex: '^.*secrets\.(json|yml)'
    key_groups:
      - age:
          - *user_ethan
          - *host_eMac
