# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  vscode-extensions-bbenoist-nix = {
    pname = "vscode-extensions-bbenoist-nix";
    version = "1.0.1";
    src = fetchurl {
      url = "https://bbenoist.gallery.vsassets.io/_apis/public/gallery/publisher/bbenoist/extension/nix/1.0.1/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "nix-1.0.1.zip";
      sha256 = "sha256-qwxqOGublQeVP2qrLF94ndX/Be9oZOn+ZMCFX1yyoH0=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
  vscode-extensions-ms-vscode-atom-keybindings = {
    pname = "vscode-extensions-ms-vscode-atom-keybindings";
    version = "3.0.9";
    src = fetchurl {
      url = "https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/atom-keybindings/3.0.9/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage";
      name = "atom-keybindings-3.0.9.zip";
      sha256 = "sha256-Qey75Irpb3Y+Unbf+ppTTVoU3XGAVJD8oXN5XKJhWBI=";
    };
    license = "mit";
    homepage = "none";
    description = "none";
  };
}
